stateDiagram-v2
    [*] --> PLANNED: RESET
    PLANNED --> FINISHED: END
    PLANNED --> ROLLING_CHARACTERS: ROLL_CHARACTERS
    ROLLING_CHARACTERS --> ROLLING_TURN_ORDER: ROLL_TURN_ORDER
    ROLLING_TURN_ORDER --> SETUP: PREPARE
    SETUP --> IN_PROGRESS: START
    IN_PROGRESS --> IN_PROGRESS: TURN_START
    IN_PROGRESS --> IN_PROGRESS: TURN_PHASE_START
    IN_PROGRESS --> IN_PROGRESS: TURN_PHASE_END
    state isLimitReached <<choice>>
    IN_PROGRESS --> isLimitReached: TURN_END
    IN_PROGRESS --> FINISHED: END
    isLimitReached --> IN_PROGRESS: Coin Limit Not Reached
    isLimitReached --> LAST_TURN: Coin Limit Reached
    LAST_TURN --> LAST_TURN: TURN_START
    LAST_TURN --> LAST_TURN: TURN_PHASE_START
    LAST_TURN --> LAST_TURN: TURN_PHASE_END
    LAST_TURN --> FINISHED: TURN_END
