stateDiagram-v2
    [*] --> IDLE
    state canApply <<choice>>
    IDLE --> canApply: START_FERTILIZE (fertilizers, crops)
    canApply --> CROP_SELECTION: canFertilize($fertilizers, $crops)
    canApply --> IDLE
    CROP_SELECTION --> CROP_CONFIRM: CHOOSE_CROP (bedIndex)
    CROP_CONFIRM --> CROP_SELECTION: CONFIRM_FERTILIZE
    CROP_CONFIRM --> CROP_SELECTION: CANCEL
    CROP_SELECTION --> IDLE: END_FERTILIZE
    CROP_CONFIRM --> IDLE: END_FERTILIZE

note right of IDLE
+Init
end note

note right of [*]
define/canFertilize (f,c) => and(isPositive(coalesce(f,0)), isPositive(len(coalesce(c,[]))))
#{bedIndex = -1}
subscribe/fertilize_phase_started START_FERTILIZE ($fertilizers, $crops)
subscribe/fertilize_crop_picked CHOOSE_CROP ($bedIndex)
subscribe/fertilize_confirmed CONFIRM_FERTILIZE
subscribe/selection_cancelled CANCEL
subscribe/fertilize_phase_ended END_FERTILIZE
end note

note left of CROP_SELECTION
#{bedIndex} <= -1
end note

note left of CROP_CONFIRM
#{bedIndex} <= $bedIndex
end note
