stateDiagram-v2
    [*] --> IDLE
    state hasCrops <<choice>>
    IDLE --> hasCrops: START_HARVEST (crops)
    hasCrops --> HARVESTING: hasRipeCrops($crops)
    hasCrops --> IDLE
    HARVESTING --> IDLE: END_HARVEST

note right of IDLE
+Init
end note

note right of [*]
define/hasRipeCrops (c) => isPositive(len(filterBy(coalesce(c,[]),'reapTimer',0)))
subscribe/harvest_phase_started START_HARVEST ($crops)
subscribe/turn_phase_ended END_HARVEST
subscribe/turn_ended END_HARVEST
end note
