stateDiagram-v2
    direction LR
    [*] --> IDLE: RESET
    note right of [*]
        inject/hasAvailableMoves
        inject/isCropCard
        inject/hasPlantingEffect
        #{hand = []}
    end note
    state gotMoreCards <<choice>>
    IDLE --> gotMoreCards: START_PLAY
    gotMoreCards --> PLAYING: hasAvailableMoves(#hand)
    state isCropCard <<choice>>
    PLAYING --> isCropCard: CHOOSE_CARD (card)
    PLAYING --> PLAYING: HOVER_CARD (index)
    PLAYING --> FINISHED: SKIP
    isCropCard --> PLANTING: isCropCard($card)
    isCropCard --> TARGETING
    PLANTING --> FINISHED: SKIP
    state hasAfterPlanting <<choice>>
    PLANTING --> CROP_PLANTED: PLANT_CROP (crop)
    CROP_PLANTED --> hasAfterPlanting: PLANT_CROP (crop)
    PLANTING --> PLAYING: CANCEL_SELECTION
    hasAfterPlanting --> TARGETING: hasPlantingEffect($crop)
    hasAfterPlanting --> gotMoreCards
    TARGETING --> PLAYING: CANCEL_SELECTION
    TARGETING --> EXECUTION: EXECUTE_ACTION
    TARGETING --> FINISHED: SKIP
    EXECUTION --> gotMoreCards: EXECUTE_ACTION
    gotMoreCards --> FINISHED
    FINISHED --> [*]
    note right of IDLE
        emit/startPlay
        subscribe/startPlay START_PLAY
    end note
    note left of PLANTING
        emit/enableTargetMode (#BED_EMPTY)
    end note
    note right of EXECUTION
        emit/disableTargetMode
        emit/applyEffect
        subscribe/applyEffect EXECUTE_ACTION
    end note
    note left of TARGETING
        emit/enableTargetMode
    end note
    note left of PLAYING
        emit/enableTargetMode (#CARD_OWN)
        subscribe/forceEndPhase SKIP
    end note
    note left of CROP_PLANTED
        emit/cropPlanted
        subscribe/cropPlanted PLANT_CROP
    end note
