stateDiagram-v2
    [*] --> IDLE
    state hasCards <<choice>>
    IDLE --> hasCards: START_TRADE (hand)
    hasCards --> COLLECT: hasCardsInHand($hand)
    hasCards --> IDLE
    COLLECT --> CARD_ADDED: ADD_CARD (cardId)
    CARD_ADDED --> COLLECT: [-]
    COLLECT --> CARD_REMOVED: REMOVE_CARD (cardId)
    CARD_REMOVED --> COLLECT: [-]
    COLLECT --> OFFERED: SEND_OFFER
    OFFERED --> CHOOSING: BIDS_ARRIVED
    CHOOSING --> IDLE: ACCEPT_BID
    COLLECT --> IDLE: END_TRADE
    OFFERED --> IDLE: END_TRADE
    CHOOSING --> IDLE: END_TRADE

note right of IDLE
+Init
#{offered} <= emptyMap()
end note

note right of [*]
define/hasCardsInHand (h) => isPositive(len(coalesce(h,[])))
define/emptyMap () => omit(zip([],[]),[])
#{offered = emptyMap()}
subscribe/trade_phase_started START_TRADE ($hand)
subscribe/trade_card_added ADD_CARD ($cardId)
subscribe/trade_card_removed REMOVE_CARD ($cardId)
subscribe/trade_offer_sent SEND_OFFER
subscribe/trade_bids_gathered BIDS_ARRIVED
subscribe/trade_bid_accepted ACCEPT_BID
subscribe/trade_phase_ended END_TRADE
end note

note left of COLLECT
#{offered} <= #offered
end note

note right of CARD_ADDED
+ByPass
#{offered} <= setAttr(omit(#offered,[]), $cardId, 1)
end note

note right of CARD_REMOVED
+ByPass
#{offered} <= omit(#offered, $cardId)
end note

note left of OFFERED
#{offered} <= #offered
end note

note left of CHOOSING
#{offered} <= #offered
end note
