stateDiagram-v2
    direction LR
    [*] --> IDLE: RESET
    note right of [*]
        inject/hasCoins
        inject/hasEligibleEffectConditions
        #{coins = 0, eligibleEffects = []}
    end note
    IDLE --> FINISHED: SKIP
    note left of IDLE
        subscribe/startTrade START_TRADE
        subscribe/cropHarvested ENTER_TARGET_MODE
        subscribe/cropFertilized ENTER_TARGET_MODE
        subscribe/cropPlanted ENTER_TARGET_MODE
        subscribe/forceEndPhase SKIP
        emit/revokeTradeOffers
        emit/disableTargetMode
    end note
    state hasMoney <<choice>>
    IDLE --> hasMoney: START_TRADE
    hasMoney --> HAS_TRADE: hasCoins(#coins)
    hasMoney --> IDLE
    HAS_TRADE --> FINISHED: SKIP
    HAS_TRADE --> HAS_TRADE: CHANGE_TRADE_OFFER
    HAS_TRADE --> OFFER_SENT: MAKE_OFFER
    note left of OFFER_SENT
        emit/makeTradeOffer
    end note
    OFFER_SENT --> IDLE: CANCEL_SELECTION
    OFFER_SENT --> IDLE: OFFER_ACCEPTED
    OFFER_SENT --> FINISHED: SKIP
    state isAffected <<choice>>
    IDLE --> isAffected: ENTER_TARGET_MODE
    isAffected --> TARGETING: hasEligibleEffectConditions(#eligibleEffects)
    isAffected --> IDLE
    note left of TARGETING
        emit/enableTargetMode
    end note
    TARGETING --> IDLE: CANCEL_SELECTION
    TARGETING --> FINISHED: SKIP
    TARGETING --> EFFECT_APPLIED: APPLY_EFFECT
    note right of EFFECT_APPLIED
        emit/applyEffect
        emit/disableTargetMode
        subscribe/applyEffect APPLY_EFFECT
    end note
    EFFECT_APPLIED --> IDLE: APPLY_EFFECT
    FINISHED --> [*]
