stateDiagram-v2
    direction LR
    [*] --> IDLE
    state hasMoney <<choice>>
    IDLE --> hasMoney: OFFER_APPEARED (coins)
    hasMoney --> HAS_TRADE: isPositive($coins)
    hasMoney --> IDLE
    HAS_TRADE --> BID_SENT: MAKE_BID (coins)
    HAS_TRADE --> IDLE: OFFER_CLOSED
    BID_SENT --> IDLE: OFFER_CLOSED

note right of IDLE
+Init
end note

note right of [*]
#{bid = 0}
subscribe/trade_offer_appeared OFFER_APPEARED ($coins)
subscribe/waiting_bid_placed MAKE_BID ($coins)
subscribe/trade_offer_closed OFFER_CLOSED
end note

note left of BID_SENT
#{bid} <= $coins
end note
