stateDiagram-v2
    direction LR
    [*] --> IDLE
    state hasMoney <<choice>>
    IDLE --> hasMoney: OFFER_APPEARED (viewerId, coins)
    hasMoney --> HAS_TRADE: isPositive($coins)
    hasMoney --> IDLE
    HAS_TRADE --> BID_SENT: MAKE_BID (coins)
    HAS_TRADE --> IDLE: OFFER_CLOSED
    BID_SENT --> IDLE: OFFER_CLOSED

note right of IDLE
+Init
end note

note right of [*]
#{viewerId = 0, bid = 0, seq = 0}
subscribe/trade_offer_appeared OFFER_APPEARED ($viewerId, $coins)
subscribe/waiting_bid_placed MAKE_BID ($coins)
subscribe/trade_offer_closed OFFER_CLOSED
subscribe/turn_ended OFFER_CLOSED
end note

note left of HAS_TRADE
#{viewerId, bid, seq} <= $viewerId, 0, #seq
end note

note left of BID_SENT
#{viewerId, bid, seq} <= #viewerId, $coins, inc(#seq)
emit/waiting_bid_committed (#viewerId, #bid, #seq)
end note
