import { emitDomainEvent } from '~/app/yantrix/data/sources/UIBridgeDataSource';
import { WindowDomainEvents } from '~/app/yantrix/windowDomainEvents';

export function useCreateLobby() {
	return {
		/**
		 * Asks for a new room. The code is generated by the room service and comes
		 * back on `lobby_created`, so there is nothing to pass in.
		 */
		createLobby() {
			emitDomainEvent(WindowDomainEvents.room_create_requested, null);
		},
	};
}
